/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125404RouteImport } from './routes/{-$locale}/404'
import { Route as Char123LocaleChar125SplatRouteImport } from './routes/{-$locale}/$'
import { Route as Char123LocaleChar125DocsRouteRouteImport } from './routes/{-$locale}/docs/route'
import { Route as Char123LocaleChar125MainRouteRouteImport } from './routes/{-$locale}/_main/route'
import { Route as ApiAdminRouteRouteImport } from './routes/api/admin/route'
import { Route as Char123LocaleChar125LoginIndexRouteImport } from './routes/{-$locale}/login/index'
import { Route as ApiChatIndexRouteImport } from './routes/api/chat/index'
import { Route as Char123LocaleChar125DocsSplatRouteImport } from './routes/{-$locale}/docs/$'
import { Route as ApiPaymentDepositCheckoutRouteImport } from './routes/api/payment/deposit-checkout'
import { Route as ApiPaymentCreditCheckoutRouteImport } from './routes/api/payment/credit-checkout'
import { Route as ApiPaymentCheckoutRouteImport } from './routes/api/payment/checkout'
import { Route as ApiFileUploadRouteImport } from './routes/api/file/upload'
import { Route as ApiCreditPackagesRouteImport } from './routes/api/credit/packages'
import { Route as ApiCreditHistoryRouteImport } from './routes/api/credit/history'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAdminRolesRouteImport } from './routes/api/admin/roles'
import { Route as ApiAdminOrdersRouteImport } from './routes/api/admin/orders'
import { Route as ApiAdminCreditPackagesRouteImport } from './routes/api/admin/credit-packages'
import { Route as ApiAdminConfigRouteImport } from './routes/api/admin/config'
import { Route as Char123LocaleChar125MainAdminRouteRouteImport } from './routes/{-$locale}/_main/admin/route'
import { Route as Char123LocaleChar125MainLandingRouteRouteImport } from './routes/{-$locale}/_main/_landing/route'
import { Route as Char123LocaleChar125MainChatIndexRouteImport } from './routes/{-$locale}/_main/chat/index'
import { Route as Char123LocaleChar125MainAdminIndexRouteImport } from './routes/{-$locale}/_main/admin/index'
import { Route as Char123LocaleChar125MainLandingIndexRouteImport } from './routes/{-$locale}/_main/_landing/index'
import { Route as Char123LocaleChar125MainAdminUsersRouteImport } from './routes/{-$locale}/_main/admin/users'
import { Route as Char123LocaleChar125MainAdminOrdersRouteImport } from './routes/{-$locale}/_main/admin/orders'
import { Route as Char123LocaleChar125MainAdminCreditPackagesRouteImport } from './routes/{-$locale}/_main/admin/credit-packages'
import { Route as Char123LocaleChar125MainAdminConfigRouteImport } from './routes/{-$locale}/_main/admin/config'
import { Route as Char123LocaleChar125MainAdminAiConfigRouteImport } from './routes/{-$locale}/_main/admin/ai-config'
import { Route as Char123LocaleChar125MainLandingWaitlistRouteImport } from './routes/{-$locale}/_main/_landing/waitlist'
import { Route as Char123LocaleChar125MainLandingRoadmapRouteImport } from './routes/{-$locale}/_main/_landing/roadmap'
import { Route as Char123LocaleChar125MainLandingDepositRouteImport } from './routes/{-$locale}/_main/_landing/deposit'
import { Route as Char123LocaleChar125MainLandingContactRouteImport } from './routes/{-$locale}/_main/_landing/contact'
import { Route as Char123LocaleChar125MainLandingChatRouteImport } from './routes/{-$locale}/_main/_landing/chat'
import { Route as Char123LocaleChar125MainLandingChangelogRouteImport } from './routes/{-$locale}/_main/_landing/changelog'
import { Route as Char123LocaleChar125MainLandingAboutRouteImport } from './routes/{-$locale}/_main/_landing/about'
import { Route as ApiPaymentWebhookProviderRouteImport } from './routes/api/payment/webhook.$provider'
import { Route as ApiPaymentSubscriptionCancelRouteImport } from './routes/api/payment/subscription/cancel'
import { Route as ApiAdminUsersIdRouteImport } from './routes/api/admin/users/$id'
import { Route as Char123LocaleChar125MainLandingBlogIndexRouteImport } from './routes/{-$locale}/_main/_landing/blog/index'
import { Route as Char123LocaleChar125MainLandingLegalSlugRouteImport } from './routes/{-$locale}/_main/_landing/legal.$slug'
import { Route as Char123LocaleChar125MainLandingDepositSuccessRouteImport } from './routes/{-$locale}/_main/_landing/deposit/success'
import { Route as Char123LocaleChar125MainLandingBlogSlugRouteImport } from './routes/{-$locale}/_main/_landing/blog/$slug'
import { Route as ApiAdminUsersIdRolesRouteImport } from './routes/api/admin/users/$id/roles'
import { Route as ApiAdminUsersIdCreditsRouteImport } from './routes/api/admin/users/$id/credits'
import { Route as ApiAdminUsersIdBanRouteImport } from './routes/api/admin/users/$id/ban'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125404Route = Char123LocaleChar125404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => Char123LocaleChar125RouteRoute,
} as any)
const Char123LocaleChar125SplatRoute =
  Char123LocaleChar125SplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125DocsRouteRoute =
  Char123LocaleChar125DocsRouteRouteImport.update({
    id: '/docs',
    path: '/docs',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125MainRouteRoute =
  Char123LocaleChar125MainRouteRouteImport.update({
    id: '/_main',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const ApiAdminRouteRoute = ApiAdminRouteRouteImport.update({
  id: '/api/admin',
  path: '/api/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125LoginIndexRoute =
  Char123LocaleChar125LoginIndexRouteImport.update({
    id: '/login/',
    path: '/login/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const ApiChatIndexRoute = ApiChatIndexRouteImport.update({
  id: '/api/chat/',
  path: '/api/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125DocsSplatRoute =
  Char123LocaleChar125DocsSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => Char123LocaleChar125DocsRouteRoute,
  } as any)
const ApiPaymentDepositCheckoutRoute =
  ApiPaymentDepositCheckoutRouteImport.update({
    id: '/api/payment/deposit-checkout',
    path: '/api/payment/deposit-checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentCreditCheckoutRoute =
  ApiPaymentCreditCheckoutRouteImport.update({
    id: '/api/payment/credit-checkout',
    path: '/api/payment/credit-checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentCheckoutRoute = ApiPaymentCheckoutRouteImport.update({
  id: '/api/payment/checkout',
  path: '/api/payment/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileUploadRoute = ApiFileUploadRouteImport.update({
  id: '/api/file/upload',
  path: '/api/file/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreditPackagesRoute = ApiCreditPackagesRouteImport.update({
  id: '/api/credit/packages',
  path: '/api/credit/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreditHistoryRoute = ApiCreditHistoryRouteImport.update({
  id: '/api/credit/history',
  path: '/api/credit/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ApiAdminRouteRoute,
} as any)
const ApiAdminRolesRoute = ApiAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => ApiAdminRouteRoute,
} as any)
const ApiAdminOrdersRoute = ApiAdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ApiAdminRouteRoute,
} as any)
const ApiAdminCreditPackagesRoute = ApiAdminCreditPackagesRouteImport.update({
  id: '/credit-packages',
  path: '/credit-packages',
  getParentRoute: () => ApiAdminRouteRoute,
} as any)
const ApiAdminConfigRoute = ApiAdminConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => ApiAdminRouteRoute,
} as any)
const Char123LocaleChar125MainAdminRouteRoute =
  Char123LocaleChar125MainAdminRouteRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => Char123LocaleChar125MainRouteRoute,
  } as any)
const Char123LocaleChar125MainLandingRouteRoute =
  Char123LocaleChar125MainLandingRouteRouteImport.update({
    id: '/_landing',
    getParentRoute: () => Char123LocaleChar125MainRouteRoute,
  } as any)
const Char123LocaleChar125MainChatIndexRoute =
  Char123LocaleChar125MainChatIndexRouteImport.update({
    id: '/chat/',
    path: '/chat/',
    getParentRoute: () => Char123LocaleChar125MainRouteRoute,
  } as any)
const Char123LocaleChar125MainAdminIndexRoute =
  Char123LocaleChar125MainAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125MainAdminRouteRoute,
  } as any)
const Char123LocaleChar125MainLandingIndexRoute =
  Char123LocaleChar125MainLandingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125MainLandingRouteRoute,
  } as any)
const Char123LocaleChar125MainAdminUsersRoute =
  Char123LocaleChar125MainAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => Char123LocaleChar125MainAdminRouteRoute,
  } as any)
const Char123LocaleChar125MainAdminOrdersRoute =
  Char123LocaleChar125MainAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => Char123LocaleChar125MainAdminRouteRoute,
  } as any)
const Char123LocaleChar125MainAdminCreditPackagesRoute =
  Char123LocaleChar125MainAdminCreditPackagesRouteImport.update({
    id: '/credit-packages',
    path: '/credit-packages',
    getParentRoute: () => Char123LocaleChar125MainAdminRouteRoute,
  } as any)
const Char123LocaleChar125MainAdminConfigRoute =
  Char123LocaleChar125MainAdminConfigRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => Char123LocaleChar125MainAdminRouteRoute,
  } as any)
const Char123LocaleChar125MainAdminAiConfigRoute =
  Char123LocaleChar125MainAdminAiConfigRouteImport.update({
    id: '/ai-config',
    path: '/ai-config',
    getParentRoute: () => Char123LocaleChar125MainAdminRouteRoute,
  } as any)
const Char123LocaleChar125MainLandingWaitlistRoute =
  Char123LocaleChar125MainLandingWaitlistRouteImport.update({
    id: '/waitlist',
    path: '/waitlist',
    getParentRoute: () => Char123LocaleChar125MainLandingRouteRoute,
  } as any)
const Char123LocaleChar125MainLandingRoadmapRoute =
  Char123LocaleChar125MainLandingRoadmapRouteImport.update({
    id: '/roadmap',
    path: '/roadmap',
    getParentRoute: () => Char123LocaleChar125MainLandingRouteRoute,
  } as any)
const Char123LocaleChar125MainLandingDepositRoute =
  Char123LocaleChar125MainLandingDepositRouteImport.update({
    id: '/deposit',
    path: '/deposit',
    getParentRoute: () => Char123LocaleChar125MainLandingRouteRoute,
  } as any)
const Char123LocaleChar125MainLandingContactRoute =
  Char123LocaleChar125MainLandingContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => Char123LocaleChar125MainLandingRouteRoute,
  } as any)
const Char123LocaleChar125MainLandingChatRoute =
  Char123LocaleChar125MainLandingChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => Char123LocaleChar125MainLandingRouteRoute,
  } as any)
const Char123LocaleChar125MainLandingChangelogRoute =
  Char123LocaleChar125MainLandingChangelogRouteImport.update({
    id: '/changelog',
    path: '/changelog',
    getParentRoute: () => Char123LocaleChar125MainLandingRouteRoute,
  } as any)
const Char123LocaleChar125MainLandingAboutRoute =
  Char123LocaleChar125MainLandingAboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => Char123LocaleChar125MainLandingRouteRoute,
  } as any)
const ApiPaymentWebhookProviderRoute =
  ApiPaymentWebhookProviderRouteImport.update({
    id: '/api/payment/webhook/$provider',
    path: '/api/payment/webhook/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentSubscriptionCancelRoute =
  ApiPaymentSubscriptionCancelRouteImport.update({
    id: '/api/payment/subscription/cancel',
    path: '/api/payment/subscription/cancel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminUsersIdRoute = ApiAdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminUsersRoute,
} as any)
const Char123LocaleChar125MainLandingBlogIndexRoute =
  Char123LocaleChar125MainLandingBlogIndexRouteImport.update({
    id: '/blog/',
    path: '/blog/',
    getParentRoute: () => Char123LocaleChar125MainLandingRouteRoute,
  } as any)
const Char123LocaleChar125MainLandingLegalSlugRoute =
  Char123LocaleChar125MainLandingLegalSlugRouteImport.update({
    id: '/legal/$slug',
    path: '/legal/$slug',
    getParentRoute: () => Char123LocaleChar125MainLandingRouteRoute,
  } as any)
const Char123LocaleChar125MainLandingDepositSuccessRoute =
  Char123LocaleChar125MainLandingDepositSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => Char123LocaleChar125MainLandingDepositRoute,
  } as any)
const Char123LocaleChar125MainLandingBlogSlugRoute =
  Char123LocaleChar125MainLandingBlogSlugRouteImport.update({
    id: '/blog/$slug',
    path: '/blog/$slug',
    getParentRoute: () => Char123LocaleChar125MainLandingRouteRoute,
  } as any)
const ApiAdminUsersIdRolesRoute = ApiAdminUsersIdRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => ApiAdminUsersIdRoute,
} as any)
const ApiAdminUsersIdCreditsRoute = ApiAdminUsersIdCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => ApiAdminUsersIdRoute,
} as any)
const ApiAdminUsersIdBanRoute = ApiAdminUsersIdBanRouteImport.update({
  id: '/ban',
  path: '/ban',
  getParentRoute: () => ApiAdminUsersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125MainLandingRouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/admin': typeof ApiAdminRouteRouteWithChildren
  '/{-$locale}/docs': typeof Char123LocaleChar125DocsRouteRouteWithChildren
  '/{-$locale}/$': typeof Char123LocaleChar125SplatRoute
  '/{-$locale}/404': typeof Char123LocaleChar125404Route
  '/{-$locale}/admin': typeof Char123LocaleChar125MainAdminRouteRouteWithChildren
  '/api/admin/config': typeof ApiAdminConfigRoute
  '/api/admin/credit-packages': typeof ApiAdminCreditPackagesRoute
  '/api/admin/orders': typeof ApiAdminOrdersRoute
  '/api/admin/roles': typeof ApiAdminRolesRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/credit/history': typeof ApiCreditHistoryRoute
  '/api/credit/packages': typeof ApiCreditPackagesRoute
  '/api/file/upload': typeof ApiFileUploadRoute
  '/api/payment/checkout': typeof ApiPaymentCheckoutRoute
  '/api/payment/credit-checkout': typeof ApiPaymentCreditCheckoutRoute
  '/api/payment/deposit-checkout': typeof ApiPaymentDepositCheckoutRoute
  '/{-$locale}/docs/$': typeof Char123LocaleChar125DocsSplatRoute
  '/api/chat/': typeof ApiChatIndexRoute
  '/{-$locale}/login/': typeof Char123LocaleChar125LoginIndexRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRouteWithChildren
  '/api/payment/subscription/cancel': typeof ApiPaymentSubscriptionCancelRoute
  '/api/payment/webhook/$provider': typeof ApiPaymentWebhookProviderRoute
  '/{-$locale}/about': typeof Char123LocaleChar125MainLandingAboutRoute
  '/{-$locale}/changelog': typeof Char123LocaleChar125MainLandingChangelogRoute
  '/{-$locale}/chat': typeof Char123LocaleChar125MainLandingChatRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125MainLandingContactRoute
  '/{-$locale}/deposit': typeof Char123LocaleChar125MainLandingDepositRouteWithChildren
  '/{-$locale}/roadmap': typeof Char123LocaleChar125MainLandingRoadmapRoute
  '/{-$locale}/waitlist': typeof Char123LocaleChar125MainLandingWaitlistRoute
  '/{-$locale}/admin/ai-config': typeof Char123LocaleChar125MainAdminAiConfigRoute
  '/{-$locale}/admin/config': typeof Char123LocaleChar125MainAdminConfigRoute
  '/{-$locale}/admin/credit-packages': typeof Char123LocaleChar125MainAdminCreditPackagesRoute
  '/{-$locale}/admin/orders': typeof Char123LocaleChar125MainAdminOrdersRoute
  '/{-$locale}/admin/users': typeof Char123LocaleChar125MainAdminUsersRoute
  '/{-$locale}/': typeof Char123LocaleChar125MainLandingIndexRoute
  '/{-$locale}/admin/': typeof Char123LocaleChar125MainAdminIndexRoute
  '/{-$locale}/chat/': typeof Char123LocaleChar125MainChatIndexRoute
  '/api/admin/users/$id/ban': typeof ApiAdminUsersIdBanRoute
  '/api/admin/users/$id/credits': typeof ApiAdminUsersIdCreditsRoute
  '/api/admin/users/$id/roles': typeof ApiAdminUsersIdRolesRoute
  '/{-$locale}/blog/$slug': typeof Char123LocaleChar125MainLandingBlogSlugRoute
  '/{-$locale}/deposit/success': typeof Char123LocaleChar125MainLandingDepositSuccessRoute
  '/{-$locale}/legal/$slug': typeof Char123LocaleChar125MainLandingLegalSlugRoute
  '/{-$locale}/blog/': typeof Char123LocaleChar125MainLandingBlogIndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}': typeof Char123LocaleChar125MainLandingIndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/admin': typeof ApiAdminRouteRouteWithChildren
  '/{-$locale}/docs': typeof Char123LocaleChar125DocsRouteRouteWithChildren
  '/{-$locale}/$': typeof Char123LocaleChar125SplatRoute
  '/{-$locale}/404': typeof Char123LocaleChar125404Route
  '/api/admin/config': typeof ApiAdminConfigRoute
  '/api/admin/credit-packages': typeof ApiAdminCreditPackagesRoute
  '/api/admin/orders': typeof ApiAdminOrdersRoute
  '/api/admin/roles': typeof ApiAdminRolesRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/credit/history': typeof ApiCreditHistoryRoute
  '/api/credit/packages': typeof ApiCreditPackagesRoute
  '/api/file/upload': typeof ApiFileUploadRoute
  '/api/payment/checkout': typeof ApiPaymentCheckoutRoute
  '/api/payment/credit-checkout': typeof ApiPaymentCreditCheckoutRoute
  '/api/payment/deposit-checkout': typeof ApiPaymentDepositCheckoutRoute
  '/{-$locale}/docs/$': typeof Char123LocaleChar125DocsSplatRoute
  '/api/chat': typeof ApiChatIndexRoute
  '/{-$locale}/login': typeof Char123LocaleChar125LoginIndexRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRouteWithChildren
  '/api/payment/subscription/cancel': typeof ApiPaymentSubscriptionCancelRoute
  '/api/payment/webhook/$provider': typeof ApiPaymentWebhookProviderRoute
  '/{-$locale}/about': typeof Char123LocaleChar125MainLandingAboutRoute
  '/{-$locale}/changelog': typeof Char123LocaleChar125MainLandingChangelogRoute
  '/{-$locale}/chat': typeof Char123LocaleChar125MainChatIndexRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125MainLandingContactRoute
  '/{-$locale}/deposit': typeof Char123LocaleChar125MainLandingDepositRouteWithChildren
  '/{-$locale}/roadmap': typeof Char123LocaleChar125MainLandingRoadmapRoute
  '/{-$locale}/waitlist': typeof Char123LocaleChar125MainLandingWaitlistRoute
  '/{-$locale}/admin/ai-config': typeof Char123LocaleChar125MainAdminAiConfigRoute
  '/{-$locale}/admin/config': typeof Char123LocaleChar125MainAdminConfigRoute
  '/{-$locale}/admin/credit-packages': typeof Char123LocaleChar125MainAdminCreditPackagesRoute
  '/{-$locale}/admin/orders': typeof Char123LocaleChar125MainAdminOrdersRoute
  '/{-$locale}/admin/users': typeof Char123LocaleChar125MainAdminUsersRoute
  '/{-$locale}/admin': typeof Char123LocaleChar125MainAdminIndexRoute
  '/api/admin/users/$id/ban': typeof ApiAdminUsersIdBanRoute
  '/api/admin/users/$id/credits': typeof ApiAdminUsersIdCreditsRoute
  '/api/admin/users/$id/roles': typeof ApiAdminUsersIdRolesRoute
  '/{-$locale}/blog/$slug': typeof Char123LocaleChar125MainLandingBlogSlugRoute
  '/{-$locale}/deposit/success': typeof Char123LocaleChar125MainLandingDepositSuccessRoute
  '/{-$locale}/legal/$slug': typeof Char123LocaleChar125MainLandingLegalSlugRoute
  '/{-$locale}/blog': typeof Char123LocaleChar125MainLandingBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/admin': typeof ApiAdminRouteRouteWithChildren
  '/{-$locale}/_main': typeof Char123LocaleChar125MainRouteRouteWithChildren
  '/{-$locale}/docs': typeof Char123LocaleChar125DocsRouteRouteWithChildren
  '/{-$locale}/$': typeof Char123LocaleChar125SplatRoute
  '/{-$locale}/404': typeof Char123LocaleChar125404Route
  '/{-$locale}/_main/_landing': typeof Char123LocaleChar125MainLandingRouteRouteWithChildren
  '/{-$locale}/_main/admin': typeof Char123LocaleChar125MainAdminRouteRouteWithChildren
  '/api/admin/config': typeof ApiAdminConfigRoute
  '/api/admin/credit-packages': typeof ApiAdminCreditPackagesRoute
  '/api/admin/orders': typeof ApiAdminOrdersRoute
  '/api/admin/roles': typeof ApiAdminRolesRoute
  '/api/admin/users': typeof ApiAdminUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/credit/history': typeof ApiCreditHistoryRoute
  '/api/credit/packages': typeof ApiCreditPackagesRoute
  '/api/file/upload': typeof ApiFileUploadRoute
  '/api/payment/checkout': typeof ApiPaymentCheckoutRoute
  '/api/payment/credit-checkout': typeof ApiPaymentCreditCheckoutRoute
  '/api/payment/deposit-checkout': typeof ApiPaymentDepositCheckoutRoute
  '/{-$locale}/docs/$': typeof Char123LocaleChar125DocsSplatRoute
  '/api/chat/': typeof ApiChatIndexRoute
  '/{-$locale}/login/': typeof Char123LocaleChar125LoginIndexRoute
  '/api/admin/users/$id': typeof ApiAdminUsersIdRouteWithChildren
  '/api/payment/subscription/cancel': typeof ApiPaymentSubscriptionCancelRoute
  '/api/payment/webhook/$provider': typeof ApiPaymentWebhookProviderRoute
  '/{-$locale}/_main/_landing/about': typeof Char123LocaleChar125MainLandingAboutRoute
  '/{-$locale}/_main/_landing/changelog': typeof Char123LocaleChar125MainLandingChangelogRoute
  '/{-$locale}/_main/_landing/chat': typeof Char123LocaleChar125MainLandingChatRoute
  '/{-$locale}/_main/_landing/contact': typeof Char123LocaleChar125MainLandingContactRoute
  '/{-$locale}/_main/_landing/deposit': typeof Char123LocaleChar125MainLandingDepositRouteWithChildren
  '/{-$locale}/_main/_landing/roadmap': typeof Char123LocaleChar125MainLandingRoadmapRoute
  '/{-$locale}/_main/_landing/waitlist': typeof Char123LocaleChar125MainLandingWaitlistRoute
  '/{-$locale}/_main/admin/ai-config': typeof Char123LocaleChar125MainAdminAiConfigRoute
  '/{-$locale}/_main/admin/config': typeof Char123LocaleChar125MainAdminConfigRoute
  '/{-$locale}/_main/admin/credit-packages': typeof Char123LocaleChar125MainAdminCreditPackagesRoute
  '/{-$locale}/_main/admin/orders': typeof Char123LocaleChar125MainAdminOrdersRoute
  '/{-$locale}/_main/admin/users': typeof Char123LocaleChar125MainAdminUsersRoute
  '/{-$locale}/_main/_landing/': typeof Char123LocaleChar125MainLandingIndexRoute
  '/{-$locale}/_main/admin/': typeof Char123LocaleChar125MainAdminIndexRoute
  '/{-$locale}/_main/chat/': typeof Char123LocaleChar125MainChatIndexRoute
  '/api/admin/users/$id/ban': typeof ApiAdminUsersIdBanRoute
  '/api/admin/users/$id/credits': typeof ApiAdminUsersIdCreditsRoute
  '/api/admin/users/$id/roles': typeof ApiAdminUsersIdRolesRoute
  '/{-$locale}/_main/_landing/blog/$slug': typeof Char123LocaleChar125MainLandingBlogSlugRoute
  '/{-$locale}/_main/_landing/deposit/success': typeof Char123LocaleChar125MainLandingDepositSuccessRoute
  '/{-$locale}/_main/_landing/legal/$slug': typeof Char123LocaleChar125MainLandingLegalSlugRoute
  '/{-$locale}/_main/_landing/blog/': typeof Char123LocaleChar125MainLandingBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/admin'
    | '/{-$locale}/docs'
    | '/{-$locale}/$'
    | '/{-$locale}/404'
    | '/{-$locale}/admin'
    | '/api/admin/config'
    | '/api/admin/credit-packages'
    | '/api/admin/orders'
    | '/api/admin/roles'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/credit/history'
    | '/api/credit/packages'
    | '/api/file/upload'
    | '/api/payment/checkout'
    | '/api/payment/credit-checkout'
    | '/api/payment/deposit-checkout'
    | '/{-$locale}/docs/$'
    | '/api/chat/'
    | '/{-$locale}/login/'
    | '/api/admin/users/$id'
    | '/api/payment/subscription/cancel'
    | '/api/payment/webhook/$provider'
    | '/{-$locale}/about'
    | '/{-$locale}/changelog'
    | '/{-$locale}/chat'
    | '/{-$locale}/contact'
    | '/{-$locale}/deposit'
    | '/{-$locale}/roadmap'
    | '/{-$locale}/waitlist'
    | '/{-$locale}/admin/ai-config'
    | '/{-$locale}/admin/config'
    | '/{-$locale}/admin/credit-packages'
    | '/{-$locale}/admin/orders'
    | '/{-$locale}/admin/users'
    | '/{-$locale}/'
    | '/{-$locale}/admin/'
    | '/{-$locale}/chat/'
    | '/api/admin/users/$id/ban'
    | '/api/admin/users/$id/credits'
    | '/api/admin/users/$id/roles'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/deposit/success'
    | '/{-$locale}/legal/$slug'
    | '/{-$locale}/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/admin'
    | '/{-$locale}/docs'
    | '/{-$locale}/$'
    | '/{-$locale}/404'
    | '/api/admin/config'
    | '/api/admin/credit-packages'
    | '/api/admin/orders'
    | '/api/admin/roles'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/credit/history'
    | '/api/credit/packages'
    | '/api/file/upload'
    | '/api/payment/checkout'
    | '/api/payment/credit-checkout'
    | '/api/payment/deposit-checkout'
    | '/{-$locale}/docs/$'
    | '/api/chat'
    | '/{-$locale}/login'
    | '/api/admin/users/$id'
    | '/api/payment/subscription/cancel'
    | '/api/payment/webhook/$provider'
    | '/{-$locale}/about'
    | '/{-$locale}/changelog'
    | '/{-$locale}/chat'
    | '/{-$locale}/contact'
    | '/{-$locale}/deposit'
    | '/{-$locale}/roadmap'
    | '/{-$locale}/waitlist'
    | '/{-$locale}/admin/ai-config'
    | '/{-$locale}/admin/config'
    | '/{-$locale}/admin/credit-packages'
    | '/{-$locale}/admin/orders'
    | '/{-$locale}/admin/users'
    | '/{-$locale}/admin'
    | '/api/admin/users/$id/ban'
    | '/api/admin/users/$id/credits'
    | '/api/admin/users/$id/roles'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/deposit/success'
    | '/{-$locale}/legal/$slug'
    | '/{-$locale}/blog'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/admin'
    | '/{-$locale}/_main'
    | '/{-$locale}/docs'
    | '/{-$locale}/$'
    | '/{-$locale}/404'
    | '/{-$locale}/_main/_landing'
    | '/{-$locale}/_main/admin'
    | '/api/admin/config'
    | '/api/admin/credit-packages'
    | '/api/admin/orders'
    | '/api/admin/roles'
    | '/api/admin/users'
    | '/api/auth/$'
    | '/api/credit/history'
    | '/api/credit/packages'
    | '/api/file/upload'
    | '/api/payment/checkout'
    | '/api/payment/credit-checkout'
    | '/api/payment/deposit-checkout'
    | '/{-$locale}/docs/$'
    | '/api/chat/'
    | '/{-$locale}/login/'
    | '/api/admin/users/$id'
    | '/api/payment/subscription/cancel'
    | '/api/payment/webhook/$provider'
    | '/{-$locale}/_main/_landing/about'
    | '/{-$locale}/_main/_landing/changelog'
    | '/{-$locale}/_main/_landing/chat'
    | '/{-$locale}/_main/_landing/contact'
    | '/{-$locale}/_main/_landing/deposit'
    | '/{-$locale}/_main/_landing/roadmap'
    | '/{-$locale}/_main/_landing/waitlist'
    | '/{-$locale}/_main/admin/ai-config'
    | '/{-$locale}/_main/admin/config'
    | '/{-$locale}/_main/admin/credit-packages'
    | '/{-$locale}/_main/admin/orders'
    | '/{-$locale}/_main/admin/users'
    | '/{-$locale}/_main/_landing/'
    | '/{-$locale}/_main/admin/'
    | '/{-$locale}/_main/chat/'
    | '/api/admin/users/$id/ban'
    | '/api/admin/users/$id/credits'
    | '/api/admin/users/$id/roles'
    | '/{-$locale}/_main/_landing/blog/$slug'
    | '/{-$locale}/_main/_landing/deposit/success'
    | '/{-$locale}/_main/_landing/legal/$slug'
    | '/{-$locale}/_main/_landing/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAdminRouteRoute: typeof ApiAdminRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCreditHistoryRoute: typeof ApiCreditHistoryRoute
  ApiCreditPackagesRoute: typeof ApiCreditPackagesRoute
  ApiFileUploadRoute: typeof ApiFileUploadRoute
  ApiPaymentCheckoutRoute: typeof ApiPaymentCheckoutRoute
  ApiPaymentCreditCheckoutRoute: typeof ApiPaymentCreditCheckoutRoute
  ApiPaymentDepositCheckoutRoute: typeof ApiPaymentDepositCheckoutRoute
  ApiChatIndexRoute: typeof ApiChatIndexRoute
  ApiPaymentSubscriptionCancelRoute: typeof ApiPaymentSubscriptionCancelRoute
  ApiPaymentWebhookProviderRoute: typeof ApiPaymentWebhookProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/404': {
      id: '/{-$locale}/404'
      path: '/404'
      fullPath: '/{-$locale}/404'
      preLoaderRoute: typeof Char123LocaleChar125404RouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/$': {
      id: '/{-$locale}/$'
      path: '/$'
      fullPath: '/{-$locale}/$'
      preLoaderRoute: typeof Char123LocaleChar125SplatRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/docs': {
      id: '/{-$locale}/docs'
      path: '/docs'
      fullPath: '/{-$locale}/docs'
      preLoaderRoute: typeof Char123LocaleChar125DocsRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/_main': {
      id: '/{-$locale}/_main'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125MainRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/api/admin': {
      id: '/api/admin'
      path: '/api/admin'
      fullPath: '/api/admin'
      preLoaderRoute: typeof ApiAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/login/': {
      id: '/{-$locale}/login/'
      path: '/login'
      fullPath: '/{-$locale}/login/'
      preLoaderRoute: typeof Char123LocaleChar125LoginIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/api/chat/': {
      id: '/api/chat/'
      path: '/api/chat'
      fullPath: '/api/chat/'
      preLoaderRoute: typeof ApiChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/docs/$': {
      id: '/{-$locale}/docs/$'
      path: '/$'
      fullPath: '/{-$locale}/docs/$'
      preLoaderRoute: typeof Char123LocaleChar125DocsSplatRouteImport
      parentRoute: typeof Char123LocaleChar125DocsRouteRoute
    }
    '/api/payment/deposit-checkout': {
      id: '/api/payment/deposit-checkout'
      path: '/api/payment/deposit-checkout'
      fullPath: '/api/payment/deposit-checkout'
      preLoaderRoute: typeof ApiPaymentDepositCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/credit-checkout': {
      id: '/api/payment/credit-checkout'
      path: '/api/payment/credit-checkout'
      fullPath: '/api/payment/credit-checkout'
      preLoaderRoute: typeof ApiPaymentCreditCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/checkout': {
      id: '/api/payment/checkout'
      path: '/api/payment/checkout'
      fullPath: '/api/payment/checkout'
      preLoaderRoute: typeof ApiPaymentCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file/upload': {
      id: '/api/file/upload'
      path: '/api/file/upload'
      fullPath: '/api/file/upload'
      preLoaderRoute: typeof ApiFileUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/credit/packages': {
      id: '/api/credit/packages'
      path: '/api/credit/packages'
      fullPath: '/api/credit/packages'
      preLoaderRoute: typeof ApiCreditPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/credit/history': {
      id: '/api/credit/history'
      path: '/api/credit/history'
      fullPath: '/api/credit/history'
      preLoaderRoute: typeof ApiCreditHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof ApiAdminRouteRoute
    }
    '/api/admin/roles': {
      id: '/api/admin/roles'
      path: '/roles'
      fullPath: '/api/admin/roles'
      preLoaderRoute: typeof ApiAdminRolesRouteImport
      parentRoute: typeof ApiAdminRouteRoute
    }
    '/api/admin/orders': {
      id: '/api/admin/orders'
      path: '/orders'
      fullPath: '/api/admin/orders'
      preLoaderRoute: typeof ApiAdminOrdersRouteImport
      parentRoute: typeof ApiAdminRouteRoute
    }
    '/api/admin/credit-packages': {
      id: '/api/admin/credit-packages'
      path: '/credit-packages'
      fullPath: '/api/admin/credit-packages'
      preLoaderRoute: typeof ApiAdminCreditPackagesRouteImport
      parentRoute: typeof ApiAdminRouteRoute
    }
    '/api/admin/config': {
      id: '/api/admin/config'
      path: '/config'
      fullPath: '/api/admin/config'
      preLoaderRoute: typeof ApiAdminConfigRouteImport
      parentRoute: typeof ApiAdminRouteRoute
    }
    '/{-$locale}/_main/admin': {
      id: '/{-$locale}/_main/admin'
      path: '/admin'
      fullPath: '/{-$locale}/admin'
      preLoaderRoute: typeof Char123LocaleChar125MainAdminRouteRouteImport
      parentRoute: typeof Char123LocaleChar125MainRouteRoute
    }
    '/{-$locale}/_main/_landing': {
      id: '/{-$locale}/_main/_landing'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125MainLandingRouteRouteImport
      parentRoute: typeof Char123LocaleChar125MainRouteRoute
    }
    '/{-$locale}/_main/chat/': {
      id: '/{-$locale}/_main/chat/'
      path: '/chat'
      fullPath: '/{-$locale}/chat/'
      preLoaderRoute: typeof Char123LocaleChar125MainChatIndexRouteImport
      parentRoute: typeof Char123LocaleChar125MainRouteRoute
    }
    '/{-$locale}/_main/admin/': {
      id: '/{-$locale}/_main/admin/'
      path: '/'
      fullPath: '/{-$locale}/admin/'
      preLoaderRoute: typeof Char123LocaleChar125MainAdminIndexRouteImport
      parentRoute: typeof Char123LocaleChar125MainAdminRouteRoute
    }
    '/{-$locale}/_main/_landing/': {
      id: '/{-$locale}/_main/_landing/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125MainLandingIndexRouteImport
      parentRoute: typeof Char123LocaleChar125MainLandingRouteRoute
    }
    '/{-$locale}/_main/admin/users': {
      id: '/{-$locale}/_main/admin/users'
      path: '/users'
      fullPath: '/{-$locale}/admin/users'
      preLoaderRoute: typeof Char123LocaleChar125MainAdminUsersRouteImport
      parentRoute: typeof Char123LocaleChar125MainAdminRouteRoute
    }
    '/{-$locale}/_main/admin/orders': {
      id: '/{-$locale}/_main/admin/orders'
      path: '/orders'
      fullPath: '/{-$locale}/admin/orders'
      preLoaderRoute: typeof Char123LocaleChar125MainAdminOrdersRouteImport
      parentRoute: typeof Char123LocaleChar125MainAdminRouteRoute
    }
    '/{-$locale}/_main/admin/credit-packages': {
      id: '/{-$locale}/_main/admin/credit-packages'
      path: '/credit-packages'
      fullPath: '/{-$locale}/admin/credit-packages'
      preLoaderRoute: typeof Char123LocaleChar125MainAdminCreditPackagesRouteImport
      parentRoute: typeof Char123LocaleChar125MainAdminRouteRoute
    }
    '/{-$locale}/_main/admin/config': {
      id: '/{-$locale}/_main/admin/config'
      path: '/config'
      fullPath: '/{-$locale}/admin/config'
      preLoaderRoute: typeof Char123LocaleChar125MainAdminConfigRouteImport
      parentRoute: typeof Char123LocaleChar125MainAdminRouteRoute
    }
    '/{-$locale}/_main/admin/ai-config': {
      id: '/{-$locale}/_main/admin/ai-config'
      path: '/ai-config'
      fullPath: '/{-$locale}/admin/ai-config'
      preLoaderRoute: typeof Char123LocaleChar125MainAdminAiConfigRouteImport
      parentRoute: typeof Char123LocaleChar125MainAdminRouteRoute
    }
    '/{-$locale}/_main/_landing/waitlist': {
      id: '/{-$locale}/_main/_landing/waitlist'
      path: '/waitlist'
      fullPath: '/{-$locale}/waitlist'
      preLoaderRoute: typeof Char123LocaleChar125MainLandingWaitlistRouteImport
      parentRoute: typeof Char123LocaleChar125MainLandingRouteRoute
    }
    '/{-$locale}/_main/_landing/roadmap': {
      id: '/{-$locale}/_main/_landing/roadmap'
      path: '/roadmap'
      fullPath: '/{-$locale}/roadmap'
      preLoaderRoute: typeof Char123LocaleChar125MainLandingRoadmapRouteImport
      parentRoute: typeof Char123LocaleChar125MainLandingRouteRoute
    }
    '/{-$locale}/_main/_landing/deposit': {
      id: '/{-$locale}/_main/_landing/deposit'
      path: '/deposit'
      fullPath: '/{-$locale}/deposit'
      preLoaderRoute: typeof Char123LocaleChar125MainLandingDepositRouteImport
      parentRoute: typeof Char123LocaleChar125MainLandingRouteRoute
    }
    '/{-$locale}/_main/_landing/contact': {
      id: '/{-$locale}/_main/_landing/contact'
      path: '/contact'
      fullPath: '/{-$locale}/contact'
      preLoaderRoute: typeof Char123LocaleChar125MainLandingContactRouteImport
      parentRoute: typeof Char123LocaleChar125MainLandingRouteRoute
    }
    '/{-$locale}/_main/_landing/chat': {
      id: '/{-$locale}/_main/_landing/chat'
      path: '/chat'
      fullPath: '/{-$locale}/chat'
      preLoaderRoute: typeof Char123LocaleChar125MainLandingChatRouteImport
      parentRoute: typeof Char123LocaleChar125MainLandingRouteRoute
    }
    '/{-$locale}/_main/_landing/changelog': {
      id: '/{-$locale}/_main/_landing/changelog'
      path: '/changelog'
      fullPath: '/{-$locale}/changelog'
      preLoaderRoute: typeof Char123LocaleChar125MainLandingChangelogRouteImport
      parentRoute: typeof Char123LocaleChar125MainLandingRouteRoute
    }
    '/{-$locale}/_main/_landing/about': {
      id: '/{-$locale}/_main/_landing/about'
      path: '/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof Char123LocaleChar125MainLandingAboutRouteImport
      parentRoute: typeof Char123LocaleChar125MainLandingRouteRoute
    }
    '/api/payment/webhook/$provider': {
      id: '/api/payment/webhook/$provider'
      path: '/api/payment/webhook/$provider'
      fullPath: '/api/payment/webhook/$provider'
      preLoaderRoute: typeof ApiPaymentWebhookProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/subscription/cancel': {
      id: '/api/payment/subscription/cancel'
      path: '/api/payment/subscription/cancel'
      fullPath: '/api/payment/subscription/cancel'
      preLoaderRoute: typeof ApiPaymentSubscriptionCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users/$id': {
      id: '/api/admin/users/$id'
      path: '/$id'
      fullPath: '/api/admin/users/$id'
      preLoaderRoute: typeof ApiAdminUsersIdRouteImport
      parentRoute: typeof ApiAdminUsersRoute
    }
    '/{-$locale}/_main/_landing/blog/': {
      id: '/{-$locale}/_main/_landing/blog/'
      path: '/blog'
      fullPath: '/{-$locale}/blog/'
      preLoaderRoute: typeof Char123LocaleChar125MainLandingBlogIndexRouteImport
      parentRoute: typeof Char123LocaleChar125MainLandingRouteRoute
    }
    '/{-$locale}/_main/_landing/legal/$slug': {
      id: '/{-$locale}/_main/_landing/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/{-$locale}/legal/$slug'
      preLoaderRoute: typeof Char123LocaleChar125MainLandingLegalSlugRouteImport
      parentRoute: typeof Char123LocaleChar125MainLandingRouteRoute
    }
    '/{-$locale}/_main/_landing/deposit/success': {
      id: '/{-$locale}/_main/_landing/deposit/success'
      path: '/success'
      fullPath: '/{-$locale}/deposit/success'
      preLoaderRoute: typeof Char123LocaleChar125MainLandingDepositSuccessRouteImport
      parentRoute: typeof Char123LocaleChar125MainLandingDepositRoute
    }
    '/{-$locale}/_main/_landing/blog/$slug': {
      id: '/{-$locale}/_main/_landing/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/{-$locale}/blog/$slug'
      preLoaderRoute: typeof Char123LocaleChar125MainLandingBlogSlugRouteImport
      parentRoute: typeof Char123LocaleChar125MainLandingRouteRoute
    }
    '/api/admin/users/$id/roles': {
      id: '/api/admin/users/$id/roles'
      path: '/roles'
      fullPath: '/api/admin/users/$id/roles'
      preLoaderRoute: typeof ApiAdminUsersIdRolesRouteImport
      parentRoute: typeof ApiAdminUsersIdRoute
    }
    '/api/admin/users/$id/credits': {
      id: '/api/admin/users/$id/credits'
      path: '/credits'
      fullPath: '/api/admin/users/$id/credits'
      preLoaderRoute: typeof ApiAdminUsersIdCreditsRouteImport
      parentRoute: typeof ApiAdminUsersIdRoute
    }
    '/api/admin/users/$id/ban': {
      id: '/api/admin/users/$id/ban'
      path: '/ban'
      fullPath: '/api/admin/users/$id/ban'
      preLoaderRoute: typeof ApiAdminUsersIdBanRouteImport
      parentRoute: typeof ApiAdminUsersIdRoute
    }
  }
}

interface Char123LocaleChar125MainLandingDepositRouteChildren {
  Char123LocaleChar125MainLandingDepositSuccessRoute: typeof Char123LocaleChar125MainLandingDepositSuccessRoute
}

const Char123LocaleChar125MainLandingDepositRouteChildren: Char123LocaleChar125MainLandingDepositRouteChildren =
  {
    Char123LocaleChar125MainLandingDepositSuccessRoute:
      Char123LocaleChar125MainLandingDepositSuccessRoute,
  }

const Char123LocaleChar125MainLandingDepositRouteWithChildren =
  Char123LocaleChar125MainLandingDepositRoute._addFileChildren(
    Char123LocaleChar125MainLandingDepositRouteChildren,
  )

interface Char123LocaleChar125MainLandingRouteRouteChildren {
  Char123LocaleChar125MainLandingAboutRoute: typeof Char123LocaleChar125MainLandingAboutRoute
  Char123LocaleChar125MainLandingChangelogRoute: typeof Char123LocaleChar125MainLandingChangelogRoute
  Char123LocaleChar125MainLandingChatRoute: typeof Char123LocaleChar125MainLandingChatRoute
  Char123LocaleChar125MainLandingContactRoute: typeof Char123LocaleChar125MainLandingContactRoute
  Char123LocaleChar125MainLandingDepositRoute: typeof Char123LocaleChar125MainLandingDepositRouteWithChildren
  Char123LocaleChar125MainLandingRoadmapRoute: typeof Char123LocaleChar125MainLandingRoadmapRoute
  Char123LocaleChar125MainLandingWaitlistRoute: typeof Char123LocaleChar125MainLandingWaitlistRoute
  Char123LocaleChar125MainLandingIndexRoute: typeof Char123LocaleChar125MainLandingIndexRoute
  Char123LocaleChar125MainLandingBlogSlugRoute: typeof Char123LocaleChar125MainLandingBlogSlugRoute
  Char123LocaleChar125MainLandingLegalSlugRoute: typeof Char123LocaleChar125MainLandingLegalSlugRoute
  Char123LocaleChar125MainLandingBlogIndexRoute: typeof Char123LocaleChar125MainLandingBlogIndexRoute
}

const Char123LocaleChar125MainLandingRouteRouteChildren: Char123LocaleChar125MainLandingRouteRouteChildren =
  {
    Char123LocaleChar125MainLandingAboutRoute:
      Char123LocaleChar125MainLandingAboutRoute,
    Char123LocaleChar125MainLandingChangelogRoute:
      Char123LocaleChar125MainLandingChangelogRoute,
    Char123LocaleChar125MainLandingChatRoute:
      Char123LocaleChar125MainLandingChatRoute,
    Char123LocaleChar125MainLandingContactRoute:
      Char123LocaleChar125MainLandingContactRoute,
    Char123LocaleChar125MainLandingDepositRoute:
      Char123LocaleChar125MainLandingDepositRouteWithChildren,
    Char123LocaleChar125MainLandingRoadmapRoute:
      Char123LocaleChar125MainLandingRoadmapRoute,
    Char123LocaleChar125MainLandingWaitlistRoute:
      Char123LocaleChar125MainLandingWaitlistRoute,
    Char123LocaleChar125MainLandingIndexRoute:
      Char123LocaleChar125MainLandingIndexRoute,
    Char123LocaleChar125MainLandingBlogSlugRoute:
      Char123LocaleChar125MainLandingBlogSlugRoute,
    Char123LocaleChar125MainLandingLegalSlugRoute:
      Char123LocaleChar125MainLandingLegalSlugRoute,
    Char123LocaleChar125MainLandingBlogIndexRoute:
      Char123LocaleChar125MainLandingBlogIndexRoute,
  }

const Char123LocaleChar125MainLandingRouteRouteWithChildren =
  Char123LocaleChar125MainLandingRouteRoute._addFileChildren(
    Char123LocaleChar125MainLandingRouteRouteChildren,
  )

interface Char123LocaleChar125MainAdminRouteRouteChildren {
  Char123LocaleChar125MainAdminAiConfigRoute: typeof Char123LocaleChar125MainAdminAiConfigRoute
  Char123LocaleChar125MainAdminConfigRoute: typeof Char123LocaleChar125MainAdminConfigRoute
  Char123LocaleChar125MainAdminCreditPackagesRoute: typeof Char123LocaleChar125MainAdminCreditPackagesRoute
  Char123LocaleChar125MainAdminOrdersRoute: typeof Char123LocaleChar125MainAdminOrdersRoute
  Char123LocaleChar125MainAdminUsersRoute: typeof Char123LocaleChar125MainAdminUsersRoute
  Char123LocaleChar125MainAdminIndexRoute: typeof Char123LocaleChar125MainAdminIndexRoute
}

const Char123LocaleChar125MainAdminRouteRouteChildren: Char123LocaleChar125MainAdminRouteRouteChildren =
  {
    Char123LocaleChar125MainAdminAiConfigRoute:
      Char123LocaleChar125MainAdminAiConfigRoute,
    Char123LocaleChar125MainAdminConfigRoute:
      Char123LocaleChar125MainAdminConfigRoute,
    Char123LocaleChar125MainAdminCreditPackagesRoute:
      Char123LocaleChar125MainAdminCreditPackagesRoute,
    Char123LocaleChar125MainAdminOrdersRoute:
      Char123LocaleChar125MainAdminOrdersRoute,
    Char123LocaleChar125MainAdminUsersRoute:
      Char123LocaleChar125MainAdminUsersRoute,
    Char123LocaleChar125MainAdminIndexRoute:
      Char123LocaleChar125MainAdminIndexRoute,
  }

const Char123LocaleChar125MainAdminRouteRouteWithChildren =
  Char123LocaleChar125MainAdminRouteRoute._addFileChildren(
    Char123LocaleChar125MainAdminRouteRouteChildren,
  )

interface Char123LocaleChar125MainRouteRouteChildren {
  Char123LocaleChar125MainLandingRouteRoute: typeof Char123LocaleChar125MainLandingRouteRouteWithChildren
  Char123LocaleChar125MainAdminRouteRoute: typeof Char123LocaleChar125MainAdminRouteRouteWithChildren
  Char123LocaleChar125MainChatIndexRoute: typeof Char123LocaleChar125MainChatIndexRoute
}

const Char123LocaleChar125MainRouteRouteChildren: Char123LocaleChar125MainRouteRouteChildren =
  {
    Char123LocaleChar125MainLandingRouteRoute:
      Char123LocaleChar125MainLandingRouteRouteWithChildren,
    Char123LocaleChar125MainAdminRouteRoute:
      Char123LocaleChar125MainAdminRouteRouteWithChildren,
    Char123LocaleChar125MainChatIndexRoute:
      Char123LocaleChar125MainChatIndexRoute,
  }

const Char123LocaleChar125MainRouteRouteWithChildren =
  Char123LocaleChar125MainRouteRoute._addFileChildren(
    Char123LocaleChar125MainRouteRouteChildren,
  )

interface Char123LocaleChar125DocsRouteRouteChildren {
  Char123LocaleChar125DocsSplatRoute: typeof Char123LocaleChar125DocsSplatRoute
}

const Char123LocaleChar125DocsRouteRouteChildren: Char123LocaleChar125DocsRouteRouteChildren =
  {
    Char123LocaleChar125DocsSplatRoute: Char123LocaleChar125DocsSplatRoute,
  }

const Char123LocaleChar125DocsRouteRouteWithChildren =
  Char123LocaleChar125DocsRouteRoute._addFileChildren(
    Char123LocaleChar125DocsRouteRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125MainRouteRoute: typeof Char123LocaleChar125MainRouteRouteWithChildren
  Char123LocaleChar125DocsRouteRoute: typeof Char123LocaleChar125DocsRouteRouteWithChildren
  Char123LocaleChar125SplatRoute: typeof Char123LocaleChar125SplatRoute
  Char123LocaleChar125404Route: typeof Char123LocaleChar125404Route
  Char123LocaleChar125LoginIndexRoute: typeof Char123LocaleChar125LoginIndexRoute
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125MainRouteRoute:
      Char123LocaleChar125MainRouteRouteWithChildren,
    Char123LocaleChar125DocsRouteRoute:
      Char123LocaleChar125DocsRouteRouteWithChildren,
    Char123LocaleChar125SplatRoute: Char123LocaleChar125SplatRoute,
    Char123LocaleChar125404Route: Char123LocaleChar125404Route,
    Char123LocaleChar125LoginIndexRoute: Char123LocaleChar125LoginIndexRoute,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

interface ApiAdminUsersIdRouteChildren {
  ApiAdminUsersIdBanRoute: typeof ApiAdminUsersIdBanRoute
  ApiAdminUsersIdCreditsRoute: typeof ApiAdminUsersIdCreditsRoute
  ApiAdminUsersIdRolesRoute: typeof ApiAdminUsersIdRolesRoute
}

const ApiAdminUsersIdRouteChildren: ApiAdminUsersIdRouteChildren = {
  ApiAdminUsersIdBanRoute: ApiAdminUsersIdBanRoute,
  ApiAdminUsersIdCreditsRoute: ApiAdminUsersIdCreditsRoute,
  ApiAdminUsersIdRolesRoute: ApiAdminUsersIdRolesRoute,
}

const ApiAdminUsersIdRouteWithChildren = ApiAdminUsersIdRoute._addFileChildren(
  ApiAdminUsersIdRouteChildren,
)

interface ApiAdminUsersRouteChildren {
  ApiAdminUsersIdRoute: typeof ApiAdminUsersIdRouteWithChildren
}

const ApiAdminUsersRouteChildren: ApiAdminUsersRouteChildren = {
  ApiAdminUsersIdRoute: ApiAdminUsersIdRouteWithChildren,
}

const ApiAdminUsersRouteWithChildren = ApiAdminUsersRoute._addFileChildren(
  ApiAdminUsersRouteChildren,
)

interface ApiAdminRouteRouteChildren {
  ApiAdminConfigRoute: typeof ApiAdminConfigRoute
  ApiAdminCreditPackagesRoute: typeof ApiAdminCreditPackagesRoute
  ApiAdminOrdersRoute: typeof ApiAdminOrdersRoute
  ApiAdminRolesRoute: typeof ApiAdminRolesRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRouteWithChildren
}

const ApiAdminRouteRouteChildren: ApiAdminRouteRouteChildren = {
  ApiAdminConfigRoute: ApiAdminConfigRoute,
  ApiAdminCreditPackagesRoute: ApiAdminCreditPackagesRoute,
  ApiAdminOrdersRoute: ApiAdminOrdersRoute,
  ApiAdminRolesRoute: ApiAdminRolesRoute,
  ApiAdminUsersRoute: ApiAdminUsersRouteWithChildren,
}

const ApiAdminRouteRouteWithChildren = ApiAdminRouteRoute._addFileChildren(
  ApiAdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAdminRouteRoute: ApiAdminRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCreditHistoryRoute: ApiCreditHistoryRoute,
  ApiCreditPackagesRoute: ApiCreditPackagesRoute,
  ApiFileUploadRoute: ApiFileUploadRoute,
  ApiPaymentCheckoutRoute: ApiPaymentCheckoutRoute,
  ApiPaymentCreditCheckoutRoute: ApiPaymentCreditCheckoutRoute,
  ApiPaymentDepositCheckoutRoute: ApiPaymentDepositCheckoutRoute,
  ApiChatIndexRoute: ApiChatIndexRoute,
  ApiPaymentSubscriptionCancelRoute: ApiPaymentSubscriptionCancelRoute,
  ApiPaymentWebhookProviderRoute: ApiPaymentWebhookProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
